### ISSUE TITLE
Implement integration testing with GitHub actions 

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/level0#20]
As described in: 
https://github.com/aztfmod/landingzones/blob/master/documentation/test/unit_test.md 
https://medium.com/@nicolas.yuen/cloud-adoption-framework-unit-and-integration-testing-with-terraform-9594630c123b 

And following this example: https://github.com/aztfmod/terraform-azurerm-caf-resource-group

**Comment by LaurentLesle** [comment]
I propose to implement the following integration tests.

For launchpad_opensource_light

### Setup
 
deploy launchpad opensource_light

### Scenarios

Test permutations in sandpit workspace

- rover /tf/caf/launchpads/launchpad_opensource_light apply -var location=westeurope
- rover /tf/caf/launchpads/launchpad_opensource_light apply -var location=westeurope -var convention=cafclassic
- rover /tf/caf/launchpads/launchpad_opensource_light apply -var location=westeurope -var convention=cafclassic =var use_prefrix=false
