### ISSUE TITLE
Resource group naming

### ISSUE THREAD

**Issue by georgeolson** [aztfmod/level0#32]
The resource group names for launchpad_opensource_light would be better without prefix and postfix.

This may be related to #27 

For example:
jdna-rg-level0-terraform-state-x5lnqPQTGjGLatNk8zbrbYgR2toz0vvLi4C9MVN7YfrOETS5w
could, and probably should, be:
rg-level0-terraform-state

**Comment by arnaudlh** [comment]
Hi @georgeolson yes, there is a naming convention and custom naming capability that we are adding in this (2005) release, due *very* soon :)
